fix build error due to gcc 10
error:
gcc -Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/generic-hardened-ld -rdynamic -std=gnu99 -Wwrite-strings -Wall -Wdeclaration-after-statement -g -ffast-math -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/generic-hardened-cc1 -fasynchronous-unwind-tables -fstack-clash-protection -D_GNU_SOURCE -include config-host.h -march=armv8-a+crc+crypto -I. -I. -DBITS_PER_LONG=64 -DFIO_VERSION='"fio-3.7"' -o t/fio-dedupe t/dedupe.o lib/rbtree.o t/log.o fio_sem.o pshared.o smalloc.o gettime.o crc/md5.o lib/memalign.o lib/bloom.o t/debug.o crc/xxhash.o t/arch.o crc/murmur3.o crc/crc32c.o crc/crc32c-intel.o crc/crc32c-arm64.o crc/fnv.o -lrbd -lrados -lrados -lnuma -lrdmacm -libverbs -lrt -laio -lz  -lm  -lpthread -ldl
/usr/bin/ld: t/arch.o:/home/abuild/rpmbuild/BUILD/fio-3.7/t/arch.c:4: multiple definition of `tsc_reliable'; gettime.o:/home/abuild/rpmbuild/BUILD/fio-3.7/gettime.c:25: first defined here